# Generated by Django 2.2 on 2019-10-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
